{"ast":null,"code":"import{useRouteError}from\"react-router-dom\";import{jsx as _jsx}from\"react/jsx-runtime\";import{jsxs as _jsxs}from\"react/jsx-runtime\";export default function ErrorPage(){var error=useRouteError();console.error(error);return/*#__PURE__*/_jsxs(\"div\",{id:\"error-page\",children:[/*#__PURE__*/_jsx(\"h1\",{children:\"Oops!\"}),/*#__PURE__*/_jsx(\"p\",{children:\"Sorry, an unexpected error has occurred.\"}),/*#__PURE__*/_jsx(\"p\",{children:/*#__PURE__*/_jsx(\"i\",{children:error.statusText||error.message})})]});}","map":{"version":3,"names":["useRouteError","ErrorPage","error","console","statusText","message"],"sources":["/Users/kamilkusakov/mydoc/PyDocs/PROJECT/social2.0/frontend/src/error-page.jsx"],"sourcesContent":["import { useRouteError } from \"react-router-dom\";\n\nexport default function ErrorPage() {\n  const error = useRouteError();\n  console.error(error);\n\n  return (\n    <div id=\"error-page\">\n      <h1>Oops!</h1>\n      <p>Sorry, an unexpected error has occurred.</p>\n      <p>\n        <i>{error.statusText || error.message}</i>\n      </p>\n    </div>\n  );\n}\n"],"mappings":"AAAA,OAASA,aAAa,KAAQ,kBAAkB,CAAC,wFAEjD,cAAe,SAASC,UAAS,EAAG,CAClC,GAAMC,MAAK,CAAGF,aAAa,EAAE,CAC7BG,OAAO,CAACD,KAAK,CAACA,KAAK,CAAC,CAEpB,mBACE,aAAK,EAAE,CAAC,YAAY,wBAClB,6BAAc,cACd,+DAA+C,cAC/C,gCACE,mBAAIA,KAAK,CAACE,UAAU,EAAIF,KAAK,CAACG,OAAO,EAAK,EACxC,GACA,CAEV"},"metadata":{},"sourceType":"module","externalDependencies":[]}